language: go

go:
  - 1.9
  # - 1.10
  # - master

cache:
  directories:
   - $HOME/proto

env:
  - PROTO_VERSION="3.5.2" PROTO_BASE="$HOME/proto" PROTO_DIR="$PROTO_BASE/$PROTO_VERSION" PATH="$PATH:$PROTO_DIR/bin"

before_install:
  - echo "pwd:$(pwd)"

install:
  - . .travis/install.sh
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
  # - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger

script:
  # Develop Mode:
  - env ARGCV_REPO_URL=https://github.com/argcv/argcv.git ./sync_proto.sh

deploy:
  - provider: script
    keep-history: true
    skip-cleanup: true
    script: bash .travis/update.sh
    on:
      branch: master


