// Code generated by protoc-gen-go. DO NOT EDIT.
// source: argcv/proto/app/manul/user.proto

package manul // import "github.com/argcv/go-argcvapis/app/manul"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/argcv/go-argcvapis/api/annotations"
import status "github.com/argcv/go-argcvapis/status/status"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserType int32

const (
	// could access everything
	// used to add/remove users
	// to/from projects
	UserType_ADMIN UserType = 0
	// used to submit job
	// for ordinary students
	UserType_USER UserType = 1
	// special authorization
	// could read project
	// but can NOT submit job
	UserType_BOT UserType = 2
)

var UserType_name = map[int32]string{
	0: "ADMIN",
	1: "USER",
	2: "BOT",
}
var UserType_value = map[string]int32{
	"ADMIN": 0,
	"USER":  1,
	"BOT":   2,
}

func (x UserType) String() string {
	return proto.EnumName(UserType_name, int32(x))
}
func (UserType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_user_be3c534a3c80d404, []int{0}
}

type User struct {
	Id       string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserType UserType `protobuf:"varint,2,opt,name=user_type,json=userType,proto3,enum=argcv.app.manul.UserType" json:"user_type,omitempty"`
	// user name, may corresponding to some
	// external user name
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName string `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Note: it should be post-processed before return to client
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_be3c534a3c80d404, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUserType() UserType {
	if m != nil {
		return m.UserType
	}
	return UserType_ADMIN
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Users struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Size                 int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total                int32    `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_be3c534a3c80d404, []int{1}
}
func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (dst *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(dst, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Users) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Users) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Users) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type ListUsersRequest struct {
	// The standard list filter.
	Filter string `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	// offset
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// size
	Size int32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// User Id
	UserId string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// User Secret
	Secret               string   `protobuf:"bytes,5,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_be3c534a3c80d404, []int{2}
}
func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (dst *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(dst, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

func (m *ListUsersRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ListUsersRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListUsersRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListUsersRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListUsersRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type ListUsersResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// The operation result, which can be either an `error` or a valid `projects`.
	// If `success` == `true`, `users` is set
	// If `success` == `false`, `error` is set.
	//
	// Types that are valid to be assigned to Result:
	//	*ListUsersResponse_Error
	//	*ListUsersResponse_Users
	Result               isListUsersResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_be3c534a3c80d404, []int{3}
}
func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (dst *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(dst, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

type isListUsersResponse_Result interface {
	isListUsersResponse_Result()
}

type ListUsersResponse_Error struct {
	Error *status.Status `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}
type ListUsersResponse_Users struct {
	Users *Users `protobuf:"bytes,4,opt,name=users,proto3,oneof"`
}

func (*ListUsersResponse_Error) isListUsersResponse_Result() {}
func (*ListUsersResponse_Users) isListUsersResponse_Result() {}

func (m *ListUsersResponse) GetResult() isListUsersResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ListUsersResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListUsersResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListUsersResponse) GetError() *status.Status {
	if x, ok := m.GetResult().(*ListUsersResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (m *ListUsersResponse) GetUsers() *Users {
	if x, ok := m.GetResult().(*ListUsersResponse_Users); ok {
		return x.Users
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ListUsersResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ListUsersResponse_OneofMarshaler, _ListUsersResponse_OneofUnmarshaler, _ListUsersResponse_OneofSizer, []interface{}{
		(*ListUsersResponse_Error)(nil),
		(*ListUsersResponse_Users)(nil),
	}
}

func _ListUsersResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ListUsersResponse)
	// result
	switch x := m.Result.(type) {
	case *ListUsersResponse_Error:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case *ListUsersResponse_Users:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Users); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ListUsersResponse.Result has unexpected type %T", x)
	}
	return nil
}

func _ListUsersResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ListUsersResponse)
	switch tag {
	case 3: // result.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(status.Status)
		err := b.DecodeMessage(msg)
		m.Result = &ListUsersResponse_Error{msg}
		return true, err
	case 4: // result.users
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Users)
		err := b.DecodeMessage(msg)
		m.Result = &ListUsersResponse_Users{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ListUsersResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ListUsersResponse)
	// result
	switch x := m.Result.(type) {
	case *ListUsersResponse_Error:
		s := proto.Size(x.Error)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ListUsersResponse_Users:
		s := proto.Size(x.Users)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CreateUserRequest struct {
	// required
	Name        string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName string   `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email       string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	UserType    UserType `protobuf:"varint,4,opt,name=user_type,json=userType,proto3,enum=argcv.app.manul.UserType" json:"user_type,omitempty"`
	// Your(Admin's) User Id
	UserId string `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Your(Admin's) User Secret
	Secret               string   `protobuf:"bytes,6,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_be3c534a3c80d404, []int{4}
}
func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(dst, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetUserType() UserType {
	if m != nil {
		return m.UserType
	}
	return UserType_ADMIN
}

func (m *CreateUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateUserRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type CreateUserResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Result:
	//	*CreateUserResponse_Error
	//	*CreateUserResponse_User
	Result               isCreateUserResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_be3c534a3c80d404, []int{5}
}
func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (dst *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(dst, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

type isCreateUserResponse_Result interface {
	isCreateUserResponse_Result()
}

type CreateUserResponse_Error struct {
	Error *status.Status `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}
type CreateUserResponse_User struct {
	User *User `protobuf:"bytes,4,opt,name=user,proto3,oneof"`
}

func (*CreateUserResponse_Error) isCreateUserResponse_Result() {}
func (*CreateUserResponse_User) isCreateUserResponse_Result()  {}

func (m *CreateUserResponse) GetResult() isCreateUserResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CreateUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateUserResponse) GetError() *status.Status {
	if x, ok := m.GetResult().(*CreateUserResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (m *CreateUserResponse) GetUser() *User {
	if x, ok := m.GetResult().(*CreateUserResponse_User); ok {
		return x.User
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CreateUserResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CreateUserResponse_OneofMarshaler, _CreateUserResponse_OneofUnmarshaler, _CreateUserResponse_OneofSizer, []interface{}{
		(*CreateUserResponse_Error)(nil),
		(*CreateUserResponse_User)(nil),
	}
}

func _CreateUserResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CreateUserResponse)
	// result
	switch x := m.Result.(type) {
	case *CreateUserResponse_Error:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case *CreateUserResponse_User:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.User); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("CreateUserResponse.Result has unexpected type %T", x)
	}
	return nil
}

func _CreateUserResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CreateUserResponse)
	switch tag {
	case 3: // result.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(status.Status)
		err := b.DecodeMessage(msg)
		m.Result = &CreateUserResponse_Error{msg}
		return true, err
	case 4: // result.user
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(User)
		err := b.DecodeMessage(msg)
		m.Result = &CreateUserResponse_User{msg}
		return true, err
	default:
		return false, nil
	}
}

func _CreateUserResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CreateUserResponse)
	// result
	switch x := m.Result.(type) {
	case *CreateUserResponse_Error:
		s := proto.Size(x.Error)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CreateUserResponse_User:
		s := proto.Size(x.User)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type UpdateUserRequest struct {
	// Target User Id
	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Your(Admin's) User Id
	// You can leave it as empty if you are updating yourself
	// An ordinary(Non-Admin) user can NOT change email ~TODO: discussing~
	UserId string `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Your(Admin's) User Secret
	Secret               string   `protobuf:"bytes,6,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_be3c534a3c80d404, []int{6}
}
func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(dst, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateUserRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type UpdateUserResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// The operation result, which can be either an `error` or a valid `projects`.
	// If `success` == `true`, `user` is set
	// If `success` == `false`, `error` is set.
	//
	// Types that are valid to be assigned to Result:
	//	*UpdateUserResponse_Error
	//	*UpdateUserResponse_User
	Result               isUpdateUserResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_be3c534a3c80d404, []int{7}
}
func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(dst, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

type isUpdateUserResponse_Result interface {
	isUpdateUserResponse_Result()
}

type UpdateUserResponse_Error struct {
	Error *status.Status `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}
type UpdateUserResponse_User struct {
	User *User `protobuf:"bytes,4,opt,name=user,proto3,oneof"`
}

func (*UpdateUserResponse_Error) isUpdateUserResponse_Result() {}
func (*UpdateUserResponse_User) isUpdateUserResponse_Result()  {}

func (m *UpdateUserResponse) GetResult() isUpdateUserResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *UpdateUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdateUserResponse) GetError() *status.Status {
	if x, ok := m.GetResult().(*UpdateUserResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (m *UpdateUserResponse) GetUser() *User {
	if x, ok := m.GetResult().(*UpdateUserResponse_User); ok {
		return x.User
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UpdateUserResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _UpdateUserResponse_OneofMarshaler, _UpdateUserResponse_OneofUnmarshaler, _UpdateUserResponse_OneofSizer, []interface{}{
		(*UpdateUserResponse_Error)(nil),
		(*UpdateUserResponse_User)(nil),
	}
}

func _UpdateUserResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UpdateUserResponse)
	// result
	switch x := m.Result.(type) {
	case *UpdateUserResponse_Error:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case *UpdateUserResponse_User:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.User); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("UpdateUserResponse.Result has unexpected type %T", x)
	}
	return nil
}

func _UpdateUserResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UpdateUserResponse)
	switch tag {
	case 3: // result.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(status.Status)
		err := b.DecodeMessage(msg)
		m.Result = &UpdateUserResponse_Error{msg}
		return true, err
	case 4: // result.user
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(User)
		err := b.DecodeMessage(msg)
		m.Result = &UpdateUserResponse_User{msg}
		return true, err
	default:
		return false, nil
	}
}

func _UpdateUserResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*UpdateUserResponse)
	// result
	switch x := m.Result.(type) {
	case *UpdateUserResponse_Error:
		s := proto.Size(x.Error)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UpdateUserResponse_User:
		s := proto.Size(x.User)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GetUserRequest struct {
	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Your(Admin's) User Id
	// You can leave it as empty if you are updating yourself
	UserId string `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Your(Admin's) User Secret
	Secret               string   `protobuf:"bytes,6,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_be3c534a3c80d404, []int{8}
}
func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(dst, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetUserRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type GetUserResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// The operation result, which can be either an `error` or a valid `projects`.
	// If `success` == `true`, `user` is set
	// If `success` == `false`, `error` is set.
	//
	// Types that are valid to be assigned to Result:
	//	*GetUserResponse_Error
	//	*GetUserResponse_User
	Result               isGetUserResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_be3c534a3c80d404, []int{9}
}
func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (dst *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(dst, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

type isGetUserResponse_Result interface {
	isGetUserResponse_Result()
}

type GetUserResponse_Error struct {
	Error *status.Status `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}
type GetUserResponse_User struct {
	User *User `protobuf:"bytes,4,opt,name=user,proto3,oneof"`
}

func (*GetUserResponse_Error) isGetUserResponse_Result() {}
func (*GetUserResponse_User) isGetUserResponse_Result()  {}

func (m *GetUserResponse) GetResult() isGetUserResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetUserResponse) GetError() *status.Status {
	if x, ok := m.GetResult().(*GetUserResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (m *GetUserResponse) GetUser() *User {
	if x, ok := m.GetResult().(*GetUserResponse_User); ok {
		return x.User
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GetUserResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GetUserResponse_OneofMarshaler, _GetUserResponse_OneofUnmarshaler, _GetUserResponse_OneofSizer, []interface{}{
		(*GetUserResponse_Error)(nil),
		(*GetUserResponse_User)(nil),
	}
}

func _GetUserResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GetUserResponse)
	// result
	switch x := m.Result.(type) {
	case *GetUserResponse_Error:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case *GetUserResponse_User:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.User); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GetUserResponse.Result has unexpected type %T", x)
	}
	return nil
}

func _GetUserResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GetUserResponse)
	switch tag {
	case 3: // result.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(status.Status)
		err := b.DecodeMessage(msg)
		m.Result = &GetUserResponse_Error{msg}
		return true, err
	case 4: // result.user
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(User)
		err := b.DecodeMessage(msg)
		m.Result = &GetUserResponse_User{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GetUserResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GetUserResponse)
	// result
	switch x := m.Result.(type) {
	case *GetUserResponse_Error:
		s := proto.Size(x.Error)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GetUserResponse_User:
		s := proto.Size(x.User)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type DeleteUserRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Your(Admin's) User Id
	// You can leave it as empty if you are updating yourself
	UserId string `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Your(Admin's) User Secret
	Secret               string   `protobuf:"bytes,6,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_be3c534a3c80d404, []int{10}
}
func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(dst, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DeleteUserRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type DeleteUserResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// error message
	Error                *status.Status `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_be3c534a3c80d404, []int{11}
}
func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(dst, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DeleteUserResponse) GetError() *status.Status {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "argcv.app.manul.User")
	proto.RegisterType((*Users)(nil), "argcv.app.manul.Users")
	proto.RegisterType((*ListUsersRequest)(nil), "argcv.app.manul.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "argcv.app.manul.ListUsersResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "argcv.app.manul.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "argcv.app.manul.CreateUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "argcv.app.manul.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "argcv.app.manul.UpdateUserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "argcv.app.manul.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "argcv.app.manul.GetUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "argcv.app.manul.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "argcv.app.manul.DeleteUserResponse")
	proto.RegisterEnum("argcv.app.manul.UserType", UserType_name, UserType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/argcv.app.manul.UserService/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/argcv.app.manul.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/argcv.app.manul.UserService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/argcv.app.manul.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/argcv.app.manul.UserService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/argcv.app.manul.UserService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/argcv.app.manul.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/argcv.app.manul.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/argcv.app.manul.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/argcv.app.manul.UserService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "argcv.app.manul.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUsers",
			Handler:    _UserService_ListUsers_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "argcv/proto/app/manul/user.proto",
}

func init() {
	proto.RegisterFile("argcv/proto/app/manul/user.proto", fileDescriptor_user_be3c534a3c80d404)
}

var fileDescriptor_user_be3c534a3c80d404 = []byte{
	// 816 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x4d, 0x6f, 0xe2, 0x46,
	0x18, 0xce, 0x80, 0xcd, 0xc7, 0x4b, 0x1b, 0x60, 0x94, 0xa4, 0x0e, 0x97, 0x10, 0x57, 0xaa, 0x10,
	0x69, 0xb0, 0x4a, 0xa5, 0x1e, 0xd2, 0x53, 0x69, 0xaa, 0x26, 0x52, 0x9b, 0x46, 0x26, 0x39, 0x94,
	0x4b, 0xe4, 0x98, 0x09, 0xb1, 0x64, 0xb0, 0xe3, 0x19, 0x23, 0xa5, 0x88, 0x4b, 0x2f, 0xfd, 0x01,
	0x3d, 0xf6, 0x1f, 0x54, 0x8a, 0xfa, 0x3b, 0x7a, 0xde, 0xbf, 0xb0, 0x3f, 0x61, 0x0f, 0x7b, 0x5c,
	0xcd, 0x78, 0x00, 0x83, 0x1d, 0x94, 0xec, 0x6a, 0x57, 0xb9, 0xc0, 0xbc, 0x33, 0x8f, 0xdf, 0xe7,
	0x99, 0x67, 0xde, 0xf9, 0x80, 0xba, 0x15, 0x0c, 0xec, 0xb1, 0xe1, 0x07, 0x1e, 0xf3, 0x0c, 0xcb,
	0xf7, 0x8d, 0xa1, 0x35, 0x0a, 0x5d, 0x23, 0xa4, 0x24, 0x68, 0x89, 0x4e, 0x5c, 0x16, 0x88, 0x96,
	0xe5, 0xfb, 0x2d, 0x31, 0x56, 0xdb, 0x5f, 0xfe, 0xc4, 0x31, 0xac, 0xd1, 0xc8, 0x63, 0x16, 0x73,
	0xbc, 0x11, 0x8d, 0xbe, 0xa9, 0xed, 0xc5, 0x21, 0x94, 0x59, 0x2c, 0xa4, 0xf2, 0x2f, 0x02, 0xe8,
	0xff, 0x20, 0x50, 0x2e, 0x29, 0x09, 0xf0, 0x26, 0x64, 0x9c, 0xbe, 0x86, 0xea, 0xa8, 0x51, 0x34,
	0x33, 0x4e, 0x1f, 0x7f, 0x07, 0x45, 0xce, 0x7d, 0xc5, 0xee, 0x7d, 0xa2, 0x65, 0xea, 0xa8, 0xb1,
	0xd9, 0xde, 0x6d, 0xad, 0x28, 0x68, 0xf1, 0x2f, 0x2f, 0xee, 0x7d, 0x62, 0x16, 0x42, 0xd9, 0xc2,
	0x18, 0x94, 0x91, 0x35, 0x24, 0x5a, 0x56, 0x64, 0x12, 0x6d, 0xbc, 0x0f, 0x9f, 0xf5, 0x1d, 0xea,
	0xbb, 0xd6, 0xfd, 0x95, 0x18, 0x53, 0xc4, 0x58, 0x49, 0xf6, 0x9d, 0x71, 0xc8, 0x16, 0xa8, 0x64,
	0x68, 0x39, 0xae, 0xa6, 0x8a, 0xb1, 0x28, 0xd0, 0xc7, 0xa0, 0x72, 0x0a, 0x8a, 0x0f, 0x40, 0xe5,
	0x0c, 0x54, 0x43, 0xf5, 0x6c, 0xa3, 0xd4, 0xde, 0x4e, 0x55, 0x62, 0x46, 0x18, 0xbc, 0x03, 0x39,
	0xef, 0xe6, 0x86, 0x12, 0x26, 0x74, 0xab, 0xa6, 0x8c, 0xb8, 0x34, 0xea, 0xfc, 0x11, 0x49, 0x53,
	0x4d, 0xd1, 0xe6, 0xbc, 0xcc, 0x63, 0x96, 0x2b, 0x34, 0xa9, 0x66, 0x14, 0xe8, 0x7f, 0x21, 0xa8,
	0xfc, 0xe2, 0x50, 0x26, 0xc8, 0x4d, 0x72, 0x17, 0x12, 0xca, 0x78, 0xda, 0x1b, 0xc7, 0x65, 0x24,
	0x90, 0x2e, 0xc9, 0xe8, 0x59, 0x74, 0x5f, 0x40, 0x5e, 0xb8, 0xea, 0xf4, 0xa5, 0x09, 0x39, 0x1e,
	0x9e, 0xf6, 0x79, 0x12, 0x4a, 0xec, 0x80, 0x30, 0x69, 0x80, 0x8c, 0xf4, 0xff, 0x10, 0x54, 0x63,
	0x4a, 0xa8, 0xef, 0x8d, 0x28, 0xc1, 0x1a, 0xe4, 0x69, 0x68, 0xdb, 0x84, 0x52, 0xa1, 0xa5, 0x60,
	0xce, 0x42, 0x3e, 0x32, 0x24, 0x94, 0x5a, 0x83, 0x68, 0xd1, 0x8a, 0xe6, 0x2c, 0xc4, 0x5f, 0x83,
	0x4a, 0x82, 0xc0, 0x0b, 0x84, 0x9e, 0x52, 0x7b, 0x4b, 0x5a, 0x28, 0xab, 0xa1, 0x2b, 0xfe, 0x4e,
	0x36, 0xcc, 0x08, 0x84, 0x5b, 0x33, 0xc3, 0x15, 0x81, 0xde, 0x49, 0x35, 0x5c, 0xe0, 0x05, 0xac,
	0x53, 0x80, 0x5c, 0x40, 0x68, 0xe8, 0x32, 0xfd, 0x7f, 0x04, 0xd5, 0x1f, 0x03, 0x62, 0x31, 0x22,
	0xd6, 0x44, 0x9a, 0x37, 0x2b, 0x0b, 0xb4, 0xa6, 0x2c, 0x32, 0x6b, 0xca, 0x22, 0x1b, 0x2b, 0x8b,
	0xe5, 0xda, 0x54, 0x9e, 0x5e, 0x9b, 0x31, 0xf7, 0xd5, 0x47, 0xdc, 0xcf, 0x2d, 0xb9, 0xff, 0x80,
	0x00, 0xc7, 0xe7, 0xf2, 0xc9, 0xec, 0x3f, 0x00, 0x85, 0x4b, 0x93, 0xee, 0xa7, 0x97, 0xfb, 0xc9,
	0x86, 0x29, 0x40, 0x31, 0xef, 0x6f, 0xa1, 0x7a, 0xe9, 0xf7, 0x57, 0xac, 0x5f, 0xdd, 0xd9, 0xb3,
	0xa5, 0xc8, 0xc4, 0x96, 0xe2, 0xbd, 0x9c, 0x89, 0x53, 0xbd, 0x74, 0x67, 0x08, 0x6c, 0xfe, 0x4c,
	0xd8, 0x47, 0xb7, 0xe5, 0x5f, 0x04, 0xe5, 0x39, 0xcf, 0x4b, 0xf7, 0xe4, 0x02, 0xaa, 0xc7, 0xc4,
	0x25, 0xeb, 0xab, 0xe5, 0xd9, 0x16, 0x30, 0xc0, 0xf1, 0xac, 0x1f, 0x60, 0x42, 0xf3, 0x09, 0x26,
	0x48, 0x0b, 0x9a, 0x0d, 0x28, 0xcc, 0x36, 0x3c, 0x2e, 0x82, 0xfa, 0xc3, 0xf1, 0xaf, 0xa7, 0x67,
	0x95, 0x0d, 0x5c, 0x00, 0xe5, 0xb2, 0xfb, 0x93, 0x59, 0x41, 0x38, 0x0f, 0xd9, 0xce, 0x6f, 0x17,
	0x95, 0x4c, 0xfb, 0x8d, 0x02, 0x25, 0x0e, 0xed, 0x92, 0x60, 0xec, 0xd8, 0x04, 0x3f, 0x20, 0x28,
	0xce, 0x4f, 0x58, 0xbc, 0x9f, 0x30, 0x6f, 0xf5, 0x1e, 0xa8, 0xe9, 0xeb, 0x20, 0xd1, 0x74, 0xf5,
	0xdf, 0xff, 0x7c, 0xf5, 0xfa, 0xef, 0x4c, 0x17, 0x7f, 0x6e, 0x8c, 0xbf, 0x11, 0x77, 0xf8, 0x91,
	0xeb, 0x50, 0xd6, 0xd3, 0xf0, 0xce, 0x52, 0x87, 0x31, 0x89, 0xee, 0x90, 0x69, 0xaf, 0x81, 0xbf,
	0x4a, 0x1f, 0x31, 0x26, 0xd1, 0x75, 0x32, 0x35, 0x26, 0xfc, 0x06, 0x99, 0xe2, 0x3b, 0x80, 0xc5,
	0x91, 0x84, 0x93, 0x62, 0x12, 0x67, 0x6f, 0xed, 0xcb, 0xb5, 0x18, 0xa9, 0xb8, 0x26, 0x14, 0x6f,
	0xe9, 0xe5, 0xb9, 0x0c, 0x5b, 0x80, 0x8e, 0x50, 0x13, 0x7b, 0x00, 0x8b, 0xbd, 0x9e, 0x42, 0x99,
	0x38, 0x73, 0x52, 0x28, 0x93, 0x87, 0x85, 0xae, 0x09, 0x4a, 0x5c, 0x9b, 0x9b, 0x64, 0x4c, 0x9c,
	0xfe, 0x94, 0x13, 0xda, 0x90, 0x97, 0xbb, 0x08, 0xef, 0x25, 0x32, 0x2d, 0xef, 0xe3, 0x5a, 0xfd,
	0x71, 0x80, 0xe4, 0xd9, 0x16, 0x3c, 0x65, 0xbc, 0xcc, 0x83, 0x5d, 0x80, 0x45, 0xa1, 0xa6, 0xcc,
	0x2a, 0xb1, 0x37, 0x52, 0x66, 0x95, 0xac, 0xf4, 0x19, 0x5b, 0x73, 0x99, 0xad, 0xd3, 0x83, 0x5d,
	0xdb, 0x1b, 0xca, 0x04, 0xe2, 0xed, 0xb5, 0x48, 0xd3, 0x29, 0xf2, 0x0c, 0xe7, 0xbc, 0xf3, 0x1c,
	0xf5, 0x0e, 0x07, 0x0e, 0xbb, 0x0d, 0xaf, 0x5b, 0xb6, 0x37, 0x34, 0xa2, 0xe7, 0xdb, 0xc0, 0x3b,
	0x14, 0x0d, 0xcb, 0x77, 0xe8, 0xe2, 0x6d, 0xf8, 0xbd, 0xf8, 0x7d, 0x8b, 0xd0, 0x75, 0x4e, 0xe4,
	0xfb, 0xf6, 0x5d, 0x00, 0x00, 0x00, 0xff, 0xff, 0xca, 0xe4, 0x5f, 0x31, 0x44, 0x0a, 0x00, 0x00,
}
