// Code generated by protoc-gen-go. DO NOT EDIT.
// source: argcv/proto/status/status.proto

package status

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import errcodes "github.com/argcv/go-argcvapis/status/errcodes"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The `Status` type defines a logical error model that is suitable for different
// programming environments, including REST APIs and RPC APIs. It is used by
// [gRPC](https://github.com/grpc). The error model is designed to be:
//
// - Simple to use and understand for most users
// - Flexible enough to meet unexpected needs
//
// # Overview
//
// The `Status` message contains three pieces of data: error code, error message,
// and error details. The error code should be an enum value of
// [google.rpc.Code][google.rpc.Code], but it may accept additional error codes if needed.  The
// error message should be a developer-facing English message that helps
// developers *understand* and *resolve* the error. If a localized user-facing
// error message is needed, put the localized message in the error details or
// localize it in the client. The optional error details may contain arbitrary
// information about the error. There is a predefined set of error detail types
// in the package `google.rpc` that can be used for common error conditions.
//
// # Language mapping
//
// The `Status` message is the logical representation of the error model, but it
// is not necessarily the actual wire format. When the `Status` message is
// exposed in different client libraries and different wire protocols, it can be
// mapped differently. For example, it will likely be mapped to some exceptions
// in Java, but more likely mapped to some error codes in C.
//
// # Other uses
//
// The error model and the `Status` message can be used in a variety of
// environments, either with or without APIs, to provide a
// consistent developer experience across different environments.
//
// Example uses of this error model include:
//
// - Partial errors. If a service needs to return partial errors to the client,
//     it may embed the `Status` in the normal response to indicate the partial
//     errors.
//
// - Workflow errors. A typical workflow has multiple steps. Each step may
//     have a `Status` message for error reporting.
//
// - Batch operations. If a client uses batch request and batch response, the
//     `Status` message should be used directly inside batch response, one for
//     each error sub-response.
//
// - Asynchronous operations. If an API call embeds asynchronous operation
//     results in its response, the status of those operations should be
//     represented directly using the `Status` message.
//
// - Logging. If some API errors are stored in logs, the message `Status` could
//     be used directly after any stripping needed for security/privacy reasons.
type Status struct {
	// The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
	Code errcodes.Code `protobuf:"varint,1,opt,name=code,proto3,enum=argcv.error.Code" json:"code,omitempty"`
	// A developer-facing error message, which should be in English. Any
	// user-facing error message should be localized and sent in the
	// [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// A list of messages that carry the error details.  There is a common set of
	// message types for APIs to use.
	Details              []*any.Any `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cd37c552455a97f, []int{0}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() errcodes.Code {
	if m != nil {
		return m.Code
	}
	return errcodes.Code_OK
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Status) GetDetails() []*any.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

func init() {
	proto.RegisterType((*Status)(nil), "argcv.status.Status")
}

func init() { proto.RegisterFile("argcv/proto/status/status.proto", fileDescriptor_8cd37c552455a97f) }

var fileDescriptor_8cd37c552455a97f = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4f, 0x2c, 0x4a, 0x4f,
	0x2e, 0xd3, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x86, 0x52,
	0x7a, 0x60, 0x31, 0x21, 0x1e, 0xb0, 0x02, 0x3d, 0x88, 0x98, 0x94, 0x0a, 0x16, 0xe5, 0xa9, 0x45,
	0x45, 0xf9, 0x45, 0xf1, 0xc9, 0xf9, 0x29, 0xa9, 0x50, 0x3d, 0x52, 0x92, 0xe9, 0xf9, 0xf9, 0xe9,
	0x39, 0xa9, 0x10, 0x65, 0x49, 0xa5, 0x69, 0xfa, 0x89, 0x79, 0x95, 0x10, 0x29, 0xa5, 0x4a, 0x2e,
	0xb6, 0x60, 0xb0, 0x36, 0x21, 0x55, 0x2e, 0x16, 0x90, 0x1e, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x3e,
	0x23, 0x41, 0x3d, 0x88, 0x3d, 0x60, 0xc3, 0xf4, 0x9c, 0xf3, 0x53, 0x52, 0x83, 0xc0, 0xd2, 0x42,
	0x12, 0x5c, 0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x30, 0xae, 0x90, 0x1e, 0x17, 0x7b, 0x4a, 0x6a, 0x49, 0x62, 0x66, 0x4e, 0xb1, 0x04, 0xb3,
	0x02, 0xb3, 0x06, 0xb7, 0x91, 0x88, 0x1e, 0xc4, 0x5e, 0x3d, 0x98, 0xbd, 0x7a, 0x8e, 0x79, 0x95,
	0x41, 0x30, 0x45, 0x4e, 0x71, 0x5c, 0x62, 0xc9, 0xf9, 0xb9, 0x50, 0x7b, 0xc0, 0x4a, 0xa0, 0xbe,
	0x72, 0xe2, 0x86, 0x38, 0x29, 0x00, 0x24, 0x16, 0xc0, 0x18, 0x65, 0x94, 0x9e, 0x59, 0x92, 0x51,
	0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x0f, 0xf1, 0x6f, 0x7a, 0xbe, 0x2e, 0x98, 0x91, 0x58, 0x90,
	0x59, 0x8c, 0x1a, 0x4a, 0xd6, 0x10, 0xea, 0x07, 0x23, 0x63, 0x12, 0x1b, 0xd8, 0x4c, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xea, 0x2a, 0x1b, 0x53, 0x01, 0x00, 0x00,
}
