// Code generated by protoc-gen-go. DO NOT EDIT.
// source: argcv/proto/app/manul/job.proto

package job

import (
	context "context"
	fmt "fmt"
	_ "github.com/argcv/go-argcvapis/api/annotations"
	file "github.com/argcv/go-argcvapis/app/manul/file"
	user "github.com/argcv/go-argcvapis/app/manul/user"
	status "github.com/argcv/go-argcvapis/status/status"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JobProgress int32

const (
	// Job is ready
	JobProgress_OK JobProgress = 0
	// Job not found
	JobProgress_NOT_FOUND JobProgress = 1
	// Job Created but not in queue
	JobProgress_CREATED JobProgress = 2
	// Job is in queue
	JobProgress_PENDING JobProgress = 3
	// Job in in processing
	JobProgress_PROCESSING JobProgress = 4
	// Job is canceled
	JobProgress_CANCELLED JobProgress = 5
	// Processed, timeout, no response
	JobProgress_TIMEOUT JobProgress = 6
	// Process Failed
	JobProgress_FAILED JobProgress = 7
	// Invalid User
	JobProgress_PERMISSION_DENIED JobProgress = 8
	// Reserved
	JobProgress_UNKNOWN JobProgress = 9
)

var JobProgress_name = map[int32]string{
	0: "OK",
	1: "NOT_FOUND",
	2: "CREATED",
	3: "PENDING",
	4: "PROCESSING",
	5: "CANCELLED",
	6: "TIMEOUT",
	7: "FAILED",
	8: "PERMISSION_DENIED",
	9: "UNKNOWN",
}

var JobProgress_value = map[string]int32{
	"OK":                0,
	"NOT_FOUND":         1,
	"CREATED":           2,
	"PENDING":           3,
	"PROCESSING":        4,
	"CANCELLED":         5,
	"TIMEOUT":           6,
	"FAILED":            7,
	"PERMISSION_DENIED": 8,
	"UNKNOWN":           9,
}

func (x JobProgress) String() string {
	return proto.EnumName(JobProgress_name, int32(x))
}

func (JobProgress) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1b9ab124c0102e6a, []int{0}
}

type JobResult struct {
	// Job result
	Score                int32          `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Error                *status.Status `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *JobResult) Reset()         { *m = JobResult{} }
func (m *JobResult) String() string { return proto.CompactTextString(m) }
func (*JobResult) ProtoMessage()    {}
func (*JobResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9ab124c0102e6a, []int{0}
}

func (m *JobResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobResult.Unmarshal(m, b)
}
func (m *JobResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobResult.Marshal(b, m, deterministic)
}
func (m *JobResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobResult.Merge(m, src)
}
func (m *JobResult) XXX_Size() int {
	return xxx_messageInfo_JobResult.Size(m)
}
func (m *JobResult) XXX_DiscardUnknown() {
	xxx_messageInfo_JobResult.DiscardUnknown(m)
}

var xxx_messageInfo_JobResult proto.InternalMessageInfo

func (m *JobResult) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *JobResult) GetError() *status.Status {
	if m != nil {
		return m.Error
	}
	return nil
}

// Job status
type Job struct {
	// job id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// project id
	ProjectId string `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// user id
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// current progress
	Progress             JobProgress `protobuf:"varint,4,opt,name=progress,proto3,enum=argcv.app.manul.JobProgress" json:"progress,omitempty"`
	Result               *JobResult  `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	Logs                 string      `protobuf:"bytes,6,opt,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9ab124c0102e6a, []int{1}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *Job) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Job) GetProgress() JobProgress {
	if m != nil {
		return m.Progress
	}
	return JobProgress_OK
}

func (m *Job) GetResult() *JobResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Job) GetLogs() string {
	if m != nil {
		return m.Logs
	}
	return ""
}

type Jobs struct {
	Jobs                 []*Job   `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Size                 int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total                int32    `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Jobs) Reset()         { *m = Jobs{} }
func (m *Jobs) String() string { return proto.CompactTextString(m) }
func (*Jobs) ProtoMessage()    {}
func (*Jobs) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9ab124c0102e6a, []int{2}
}

func (m *Jobs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Jobs.Unmarshal(m, b)
}
func (m *Jobs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Jobs.Marshal(b, m, deterministic)
}
func (m *Jobs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Jobs.Merge(m, src)
}
func (m *Jobs) XXX_Size() int {
	return xxx_messageInfo_Jobs.Size(m)
}
func (m *Jobs) XXX_DiscardUnknown() {
	xxx_messageInfo_Jobs.DiscardUnknown(m)
}

var xxx_messageInfo_Jobs proto.InternalMessageInfo

func (m *Jobs) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func (m *Jobs) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Jobs) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Jobs) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type ListJobsRequest struct {
	// The standard list filter.
	Filter string `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	// offset
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// size
	Size int32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// User Name ($object_id or username)
	Auth                 *user.AuthToken `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListJobsRequest) Reset()         { *m = ListJobsRequest{} }
func (m *ListJobsRequest) String() string { return proto.CompactTextString(m) }
func (*ListJobsRequest) ProtoMessage()    {}
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9ab124c0102e6a, []int{3}
}

func (m *ListJobsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListJobsRequest.Unmarshal(m, b)
}
func (m *ListJobsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListJobsRequest.Marshal(b, m, deterministic)
}
func (m *ListJobsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListJobsRequest.Merge(m, src)
}
func (m *ListJobsRequest) XXX_Size() int {
	return xxx_messageInfo_ListJobsRequest.Size(m)
}
func (m *ListJobsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListJobsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListJobsRequest proto.InternalMessageInfo

func (m *ListJobsRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ListJobsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListJobsRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListJobsRequest) GetAuth() *user.AuthToken {
	if m != nil {
		return m.Auth
	}
	return nil
}

type ListJobsResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// The operation result, which can be either an `error` or a valid `jobs`.
	// If `success` == `false`, return `error`
	// If `success` == `true`, return `jobs`
	//
	// Types that are valid to be assigned to Result:
	//	*ListJobsResponse_Error
	//	*ListJobsResponse_Jobs
	Result               isListJobsResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListJobsResponse) Reset()         { *m = ListJobsResponse{} }
func (m *ListJobsResponse) String() string { return proto.CompactTextString(m) }
func (*ListJobsResponse) ProtoMessage()    {}
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9ab124c0102e6a, []int{4}
}

func (m *ListJobsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListJobsResponse.Unmarshal(m, b)
}
func (m *ListJobsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListJobsResponse.Marshal(b, m, deterministic)
}
func (m *ListJobsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListJobsResponse.Merge(m, src)
}
func (m *ListJobsResponse) XXX_Size() int {
	return xxx_messageInfo_ListJobsResponse.Size(m)
}
func (m *ListJobsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListJobsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListJobsResponse proto.InternalMessageInfo

func (m *ListJobsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListJobsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type isListJobsResponse_Result interface {
	isListJobsResponse_Result()
}

type ListJobsResponse_Error struct {
	Error *status.Status `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type ListJobsResponse_Jobs struct {
	Jobs *Jobs `protobuf:"bytes,4,opt,name=jobs,proto3,oneof"`
}

func (*ListJobsResponse_Error) isListJobsResponse_Result() {}

func (*ListJobsResponse_Jobs) isListJobsResponse_Result() {}

func (m *ListJobsResponse) GetResult() isListJobsResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ListJobsResponse) GetError() *status.Status {
	if x, ok := m.GetResult().(*ListJobsResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (m *ListJobsResponse) GetJobs() *Jobs {
	if x, ok := m.GetResult().(*ListJobsResponse_Jobs); ok {
		return x.Jobs
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ListJobsResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ListJobsResponse_Error)(nil),
		(*ListJobsResponse_Jobs)(nil),
	}
}

type CreateJobRequest struct {
	ProjectId string      `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Files     *file.Files `protobuf:"bytes,2,opt,name=files,proto3" json:"files,omitempty"`
	// User Name ($object_id or username)
	Auth                 *user.AuthToken `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateJobRequest) Reset()         { *m = CreateJobRequest{} }
func (m *CreateJobRequest) String() string { return proto.CompactTextString(m) }
func (*CreateJobRequest) ProtoMessage()    {}
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9ab124c0102e6a, []int{5}
}

func (m *CreateJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobRequest.Unmarshal(m, b)
}
func (m *CreateJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobRequest.Marshal(b, m, deterministic)
}
func (m *CreateJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobRequest.Merge(m, src)
}
func (m *CreateJobRequest) XXX_Size() int {
	return xxx_messageInfo_CreateJobRequest.Size(m)
}
func (m *CreateJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobRequest proto.InternalMessageInfo

func (m *CreateJobRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *CreateJobRequest) GetFiles() *file.Files {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *CreateJobRequest) GetAuth() *user.AuthToken {
	if m != nil {
		return m.Auth
	}
	return nil
}

type CreateJobResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// The operation result, which can be either an `error` or a valid `job`.
	// If `success` == `false`, return error
	// If `success` == `true`, return the job
	//
	// Types that are valid to be assigned to Result:
	//	*CreateJobResponse_Error
	//	*CreateJobResponse_Job
	Result               isCreateJobResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CreateJobResponse) Reset()         { *m = CreateJobResponse{} }
func (m *CreateJobResponse) String() string { return proto.CompactTextString(m) }
func (*CreateJobResponse) ProtoMessage()    {}
func (*CreateJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9ab124c0102e6a, []int{6}
}

func (m *CreateJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobResponse.Unmarshal(m, b)
}
func (m *CreateJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobResponse.Marshal(b, m, deterministic)
}
func (m *CreateJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobResponse.Merge(m, src)
}
func (m *CreateJobResponse) XXX_Size() int {
	return xxx_messageInfo_CreateJobResponse.Size(m)
}
func (m *CreateJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobResponse proto.InternalMessageInfo

func (m *CreateJobResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateJobResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type isCreateJobResponse_Result interface {
	isCreateJobResponse_Result()
}

type CreateJobResponse_Error struct {
	Error *status.Status `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type CreateJobResponse_Job struct {
	Job *Job `protobuf:"bytes,4,opt,name=job,proto3,oneof"`
}

func (*CreateJobResponse_Error) isCreateJobResponse_Result() {}

func (*CreateJobResponse_Job) isCreateJobResponse_Result() {}

func (m *CreateJobResponse) GetResult() isCreateJobResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CreateJobResponse) GetError() *status.Status {
	if x, ok := m.GetResult().(*CreateJobResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (m *CreateJobResponse) GetJob() *Job {
	if x, ok := m.GetResult().(*CreateJobResponse_Job); ok {
		return x.Job
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CreateJobResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CreateJobResponse_Error)(nil),
		(*CreateJobResponse_Job)(nil),
	}
}

type GetJobRequest struct {
	// job id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// User Name ($object_id or username)
	Auth                 *user.AuthToken `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetJobRequest) Reset()         { *m = GetJobRequest{} }
func (m *GetJobRequest) String() string { return proto.CompactTextString(m) }
func (*GetJobRequest) ProtoMessage()    {}
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9ab124c0102e6a, []int{7}
}

func (m *GetJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobRequest.Unmarshal(m, b)
}
func (m *GetJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobRequest.Marshal(b, m, deterministic)
}
func (m *GetJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobRequest.Merge(m, src)
}
func (m *GetJobRequest) XXX_Size() int {
	return xxx_messageInfo_GetJobRequest.Size(m)
}
func (m *GetJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobRequest proto.InternalMessageInfo

func (m *GetJobRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetJobRequest) GetAuth() *user.AuthToken {
	if m != nil {
		return m.Auth
	}
	return nil
}

type GetJobResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// The operation result, which can be either an `error` or a valid `job`.
	// If `success` == `false`, return error
	// If `success` == `true`, return the job
	//
	// Types that are valid to be assigned to Result:
	//	*GetJobResponse_Error
	//	*GetJobResponse_Job
	Result               isGetJobResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetJobResponse) Reset()         { *m = GetJobResponse{} }
func (m *GetJobResponse) String() string { return proto.CompactTextString(m) }
func (*GetJobResponse) ProtoMessage()    {}
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9ab124c0102e6a, []int{8}
}

func (m *GetJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobResponse.Unmarshal(m, b)
}
func (m *GetJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobResponse.Marshal(b, m, deterministic)
}
func (m *GetJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobResponse.Merge(m, src)
}
func (m *GetJobResponse) XXX_Size() int {
	return xxx_messageInfo_GetJobResponse.Size(m)
}
func (m *GetJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobResponse proto.InternalMessageInfo

func (m *GetJobResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetJobResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type isGetJobResponse_Result interface {
	isGetJobResponse_Result()
}

type GetJobResponse_Error struct {
	Error *status.Status `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type GetJobResponse_Job struct {
	Job *Job `protobuf:"bytes,4,opt,name=job,proto3,oneof"`
}

func (*GetJobResponse_Error) isGetJobResponse_Result() {}

func (*GetJobResponse_Job) isGetJobResponse_Result() {}

func (m *GetJobResponse) GetResult() isGetJobResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetJobResponse) GetError() *status.Status {
	if x, ok := m.GetResult().(*GetJobResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (m *GetJobResponse) GetJob() *Job {
	if x, ok := m.GetResult().(*GetJobResponse_Job); ok {
		return x.Job
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetJobResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetJobResponse_Error)(nil),
		(*GetJobResponse_Job)(nil),
	}
}

type CancelJobRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// User Name ($object_id or username)
	// You can only cancel your job if your are not admin
	Auth                 *user.AuthToken `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CancelJobRequest) Reset()         { *m = CancelJobRequest{} }
func (m *CancelJobRequest) String() string { return proto.CompactTextString(m) }
func (*CancelJobRequest) ProtoMessage()    {}
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9ab124c0102e6a, []int{9}
}

func (m *CancelJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelJobRequest.Unmarshal(m, b)
}
func (m *CancelJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelJobRequest.Marshal(b, m, deterministic)
}
func (m *CancelJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelJobRequest.Merge(m, src)
}
func (m *CancelJobRequest) XXX_Size() int {
	return xxx_messageInfo_CancelJobRequest.Size(m)
}
func (m *CancelJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelJobRequest proto.InternalMessageInfo

func (m *CancelJobRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CancelJobRequest) GetAuth() *user.AuthToken {
	if m != nil {
		return m.Auth
	}
	return nil
}

type CancelJobResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// The operation result, which can be either an `error` or a valid `job`.
	// If `success` == `false`, return error
	// If `success` == `true`, return job
	//
	// Types that are valid to be assigned to Result:
	//	*CancelJobResponse_Error
	//	*CancelJobResponse_Job
	Result               isCancelJobResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CancelJobResponse) Reset()         { *m = CancelJobResponse{} }
func (m *CancelJobResponse) String() string { return proto.CompactTextString(m) }
func (*CancelJobResponse) ProtoMessage()    {}
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9ab124c0102e6a, []int{10}
}

func (m *CancelJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelJobResponse.Unmarshal(m, b)
}
func (m *CancelJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelJobResponse.Marshal(b, m, deterministic)
}
func (m *CancelJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelJobResponse.Merge(m, src)
}
func (m *CancelJobResponse) XXX_Size() int {
	return xxx_messageInfo_CancelJobResponse.Size(m)
}
func (m *CancelJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelJobResponse proto.InternalMessageInfo

func (m *CancelJobResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CancelJobResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type isCancelJobResponse_Result interface {
	isCancelJobResponse_Result()
}

type CancelJobResponse_Error struct {
	Error *status.Status `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type CancelJobResponse_Job struct {
	Job *Job `protobuf:"bytes,4,opt,name=job,proto3,oneof"`
}

func (*CancelJobResponse_Error) isCancelJobResponse_Result() {}

func (*CancelJobResponse_Job) isCancelJobResponse_Result() {}

func (m *CancelJobResponse) GetResult() isCancelJobResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CancelJobResponse) GetError() *status.Status {
	if x, ok := m.GetResult().(*CancelJobResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (m *CancelJobResponse) GetJob() *Job {
	if x, ok := m.GetResult().(*CancelJobResponse_Job); ok {
		return x.Job
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CancelJobResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CancelJobResponse_Error)(nil),
		(*CancelJobResponse_Job)(nil),
	}
}

func init() {
	proto.RegisterEnum("argcv.app.manul.JobProgress", JobProgress_name, JobProgress_value)
	proto.RegisterType((*JobResult)(nil), "argcv.app.manul.JobResult")
	proto.RegisterType((*Job)(nil), "argcv.app.manul.Job")
	proto.RegisterType((*Jobs)(nil), "argcv.app.manul.Jobs")
	proto.RegisterType((*ListJobsRequest)(nil), "argcv.app.manul.ListJobsRequest")
	proto.RegisterType((*ListJobsResponse)(nil), "argcv.app.manul.ListJobsResponse")
	proto.RegisterType((*CreateJobRequest)(nil), "argcv.app.manul.CreateJobRequest")
	proto.RegisterType((*CreateJobResponse)(nil), "argcv.app.manul.CreateJobResponse")
	proto.RegisterType((*GetJobRequest)(nil), "argcv.app.manul.GetJobRequest")
	proto.RegisterType((*GetJobResponse)(nil), "argcv.app.manul.GetJobResponse")
	proto.RegisterType((*CancelJobRequest)(nil), "argcv.app.manul.CancelJobRequest")
	proto.RegisterType((*CancelJobResponse)(nil), "argcv.app.manul.CancelJobResponse")
}

func init() { proto.RegisterFile("argcv/proto/app/manul/job.proto", fileDescriptor_1b9ab124c0102e6a) }

var fileDescriptor_1b9ab124c0102e6a = []byte{
	// 915 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x41, 0x6f, 0xe3, 0x44,
	0x14, 0xee, 0x24, 0xb1, 0x9b, 0xbc, 0xb2, 0x59, 0xef, 0xd0, 0x5d, 0xb2, 0x11, 0xb0, 0x59, 0x4b,
	0x88, 0xa8, 0x2c, 0xb1, 0x28, 0x07, 0xd0, 0x22, 0x0e, 0x6d, 0xe2, 0xee, 0x26, 0xdb, 0x3a, 0xd1,
	0x24, 0x15, 0xd2, 0x72, 0xa8, 0x6c, 0x67, 0x9a, 0x3a, 0x24, 0x19, 0xe3, 0x19, 0xf7, 0x40, 0xd5,
	0x0b, 0x12, 0x57, 0x38, 0x70, 0xe3, 0x07, 0x20, 0x21, 0x7e, 0x0c, 0x07, 0x0e, 0xfc, 0x01, 0x7e,
	0x04, 0x47, 0x34, 0x63, 0x3b, 0x4d, 0xd2, 0x6c, 0xb5, 0x48, 0x68, 0xd5, 0x53, 0xfc, 0xfc, 0xbe,
	0x79, 0xef, 0x7d, 0xdf, 0xbc, 0xf7, 0x62, 0x78, 0xe4, 0x46, 0x23, 0xff, 0xdc, 0x0a, 0x23, 0x26,
	0x98, 0xe5, 0x86, 0xa1, 0x35, 0x75, 0x67, 0xf1, 0xc4, 0x1a, 0x33, 0xaf, 0xa1, 0xde, 0xe1, 0xbb,
	0x0a, 0xd0, 0x70, 0xc3, 0xb0, 0xa1, 0x5c, 0xd5, 0xc7, 0xcb, 0x27, 0x02, 0xcb, 0x9d, 0xcd, 0x98,
	0x70, 0x45, 0xc0, 0x66, 0x3c, 0x39, 0x53, 0x5d, 0x0a, 0xca, 0x85, 0x2b, 0x62, 0x9e, 0xfe, 0xa4,
	0x80, 0xda, 0xfa, 0xac, 0xa7, 0xc1, 0x84, 0xde, 0x8c, 0x88, 0x39, 0x8d, 0x12, 0x84, 0x79, 0x04,
	0xa5, 0x0e, 0xf3, 0x08, 0xe5, 0xf1, 0x44, 0xe0, 0x6d, 0xd0, 0xb8, 0xcf, 0x22, 0x5a, 0x41, 0x35,
	0x54, 0xd7, 0x48, 0x62, 0xe0, 0x1d, 0xd0, 0x68, 0x14, 0xb1, 0xa8, 0x92, 0xab, 0xa1, 0xfa, 0xd6,
	0xee, 0x76, 0x23, 0xe1, 0x92, 0x96, 0xd2, 0x57, 0x3f, 0x24, 0x81, 0x98, 0x7f, 0x20, 0xc8, 0x77,
	0x98, 0x87, 0xcb, 0x90, 0x0b, 0x86, 0x2a, 0x4c, 0x89, 0xe4, 0x82, 0x21, 0x7e, 0x0f, 0x20, 0x8c,
	0xd8, 0x98, 0xfa, 0xe2, 0x24, 0x18, 0xaa, 0x40, 0x25, 0x52, 0x4a, 0xdf, 0xb4, 0x87, 0xf8, 0x1d,
	0xd8, 0x94, 0x35, 0x49, 0x5f, 0x5e, 0xf9, 0x74, 0x69, 0xb6, 0x87, 0xf8, 0x73, 0x28, 0x86, 0x11,
	0x1b, 0x45, 0x94, 0xf3, 0x4a, 0xa1, 0x86, 0xea, 0xe5, 0xdd, 0x77, 0x1b, 0x2b, 0x52, 0x36, 0x3a,
	0xcc, 0xeb, 0xa5, 0x18, 0x32, 0x47, 0xe3, 0x5d, 0xd0, 0x23, 0xc5, 0xaa, 0xa2, 0xa9, 0xb2, 0xab,
	0xeb, 0xce, 0x25, 0xbc, 0x49, 0x8a, 0xc4, 0x18, 0x0a, 0x13, 0x36, 0xe2, 0x15, 0x5d, 0xd5, 0xa0,
	0x9e, 0xcd, 0x08, 0x0a, 0x1d, 0xe6, 0x71, 0x5c, 0x87, 0xc2, 0x98, 0x79, 0xbc, 0x82, 0x6a, 0xf9,
	0x05, 0x11, 0x96, 0xa3, 0x29, 0x04, 0x7e, 0x00, 0x3a, 0x3b, 0x3d, 0xe5, 0x54, 0x28, 0x9e, 0x1a,
	0x49, 0x2d, 0x19, 0x9d, 0x07, 0xdf, 0x51, 0xc5, 0x50, 0x23, 0xea, 0x59, 0x2a, 0x2e, 0x98, 0x70,
	0x27, 0x8a, 0x9c, 0x46, 0x12, 0xc3, 0xfc, 0x01, 0xc1, 0xdd, 0xc3, 0x80, 0x0b, 0x99, 0x98, 0xd0,
	0x6f, 0x63, 0xca, 0x85, 0x8c, 0x7a, 0x1a, 0x4c, 0x04, 0x8d, 0x52, 0x55, 0x53, 0xeb, 0x3f, 0x65,
	0x6b, 0x40, 0xc1, 0x8d, 0xc5, 0x99, 0x4a, 0xb6, 0x4e, 0x91, 0xbd, 0x58, 0x9c, 0x0d, 0xd8, 0x37,
	0x74, 0x46, 0x14, 0xce, 0xfc, 0x1d, 0x81, 0x71, 0x55, 0x07, 0x0f, 0xd9, 0x8c, 0x53, 0x5c, 0x81,
	0x4d, 0x1e, 0xfb, 0xbe, 0xbc, 0x11, 0x59, 0x49, 0x91, 0x64, 0xa6, 0xf4, 0x4c, 0x29, 0xe7, 0xee,
	0x88, 0xa6, 0x37, 0x9c, 0x99, 0xf8, 0x49, 0xd6, 0x42, 0xf9, 0x57, 0xb7, 0xd0, 0xf3, 0x8d, 0xb4,
	0x89, 0xf0, 0x47, 0xa9, 0xd4, 0x49, 0x99, 0xf7, 0xd7, 0x49, 0x2d, 0xd1, 0x0a, 0xb4, 0x5f, 0xcc,
	0xee, 0xd9, 0xfc, 0x09, 0x81, 0xd1, 0x8c, 0xa8, 0x2b, 0xa8, 0xba, 0xd9, 0x44, 0xb6, 0xe5, 0xc6,
	0x43, 0xab, 0x8d, 0xf7, 0x04, 0x34, 0x39, 0x2e, 0x3c, 0xed, 0xed, 0x07, 0xd7, 0x72, 0x1d, 0x48,
	0x2f, 0x49, 0x40, 0x73, 0xfd, 0xf2, 0xaf, 0xa9, 0xdf, 0x6f, 0x08, 0xee, 0x2d, 0x54, 0xf4, 0xc6,
	0x04, 0xac, 0x43, 0x7e, 0xcc, 0xbc, 0x54, 0xbf, 0xb5, 0xad, 0xfa, 0x7c, 0x83, 0x48, 0xc8, 0x82,
	0x7a, 0x5d, 0xb8, 0xf3, 0x8c, 0x8a, 0x05, 0xe5, 0x56, 0x47, 0x38, 0x23, 0x9f, 0x7b, 0x4d, 0xf2,
	0xbf, 0x22, 0x28, 0x67, 0x11, 0x6f, 0x35, 0x73, 0x02, 0x46, 0xd3, 0x9d, 0xf9, 0x74, 0xf2, 0x3f,
	0x92, 0x57, 0x37, 0x7f, 0x15, 0xf4, 0x36, 0xf3, 0xdf, 0xf9, 0x05, 0xc1, 0xd6, 0xc2, 0x0e, 0xc5,
	0x3a, 0xe4, 0xba, 0x2f, 0x8c, 0x0d, 0x7c, 0x07, 0x4a, 0x4e, 0x77, 0x70, 0x72, 0xd0, 0x3d, 0x76,
	0x5a, 0x06, 0xc2, 0x5b, 0xb0, 0xd9, 0x24, 0xf6, 0xde, 0xc0, 0x6e, 0x19, 0x39, 0x69, 0xf4, 0x6c,
	0xa7, 0xd5, 0x76, 0x9e, 0x19, 0x79, 0x5c, 0x06, 0xe8, 0x91, 0x6e, 0xd3, 0xee, 0xf7, 0xa5, 0x5d,
	0x90, 0x07, 0x9b, 0x7b, 0x4e, 0xd3, 0x3e, 0x3c, 0xb4, 0x5b, 0x86, 0x26, 0xb1, 0x83, 0xf6, 0x91,
	0xdd, 0x3d, 0x1e, 0x18, 0x3a, 0x06, 0xd0, 0x0f, 0xf6, 0xda, 0xd2, 0xb1, 0x89, 0xef, 0xc3, 0xbd,
	0x9e, 0x4d, 0x8e, 0xda, 0xfd, 0x7e, 0xbb, 0xeb, 0x9c, 0xb4, 0x6c, 0xa7, 0x6d, 0xb7, 0x8c, 0xa2,
	0xc4, 0x1f, 0x3b, 0x2f, 0x9c, 0xee, 0x57, 0x8e, 0x51, 0xda, 0xfd, 0x2b, 0x0f, 0xd0, 0x61, 0x5e,
	0x9f, 0x46, 0xe7, 0x81, 0x4f, 0xf1, 0x8f, 0x08, 0x8a, 0xd9, 0x46, 0xc2, 0xb5, 0x6b, 0xfc, 0x56,
	0x96, 0x66, 0xf5, 0xf1, 0x0d, 0x88, 0xe4, 0x4e, 0xcc, 0x2f, 0xbf, 0xff, 0xf3, 0xef, 0x9f, 0x73,
	0x9f, 0xe1, 0xb7, 0xac, 0xf3, 0x4f, 0xe4, 0x1f, 0xf6, 0xd3, 0x49, 0xc0, 0xc5, 0xcb, 0x0f, 0xf1,
	0x07, 0x8b, 0xb6, 0x75, 0x91, 0x6c, 0xdb, 0x4b, 0xeb, 0x22, 0x59, 0xaf, 0x97, 0xd6, 0x85, 0xdc,
	0xa8, 0x97, 0x78, 0x0a, 0xa5, 0xf9, 0x84, 0xe3, 0xeb, 0xe9, 0x56, 0xf7, 0x51, 0xd5, 0xbc, 0x09,
	0x92, 0x96, 0xf4, 0x50, 0x95, 0xf4, 0xb6, 0x59, 0xce, 0x4a, 0xf0, 0x15, 0xe4, 0x29, 0xda, 0xc1,
	0x27, 0xa0, 0x27, 0x33, 0x85, 0xdf, 0xbf, 0x16, 0x68, 0x69, 0x7c, 0xab, 0x8f, 0x5e, 0xe9, 0x4f,
	0xb3, 0x6c, 0xab, 0x2c, 0xe5, 0x39, 0x71, 0xeb, 0x22, 0x18, 0x5e, 0xe2, 0x33, 0x28, 0xcd, 0xfb,
	0x76, 0x1d, 0x9f, 0x95, 0x41, 0x59, 0xc7, 0x67, 0xb5, 0xed, 0xb3, 0x4c, 0x3b, 0x4b, 0x99, 0xf6,
	0xbf, 0x86, 0x87, 0x3e, 0x9b, 0xa6, 0xc7, 0xd5, 0xc7, 0xc8, 0x55, 0x90, 0xfd, 0x62, 0xd2, 0x90,
	0x82, 0xf5, 0xd0, 0x4b, 0x6b, 0x14, 0x88, 0xb3, 0xd8, 0x6b, 0xf8, 0x6c, 0x6a, 0x25, 0xdf, 0x33,
	0x23, 0xf6, 0xb1, 0x7a, 0x70, 0xc3, 0x80, 0x2f, 0x7f, 0x6e, 0x7d, 0x31, 0x66, 0xde, 0x3f, 0x08,
	0x79, 0xba, 0x0a, 0xf8, 0xe9, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x46, 0x7a, 0x45, 0x80, 0x99,
	0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JobServiceClient is the client API for JobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobServiceClient interface {
	// List Jobs
	ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error)
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error)
}

type jobServiceClient struct {
	cc *grpc.ClientConn
}

func NewJobServiceClient(cc *grpc.ClientConn) JobServiceClient {
	return &jobServiceClient{cc}
}

func (c *jobServiceClient) ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, "/argcv.app.manul.JobService/ListJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error) {
	out := new(CreateJobResponse)
	err := c.cc.Invoke(ctx, "/argcv.app.manul.JobService/CreateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	out := new(GetJobResponse)
	err := c.cc.Invoke(ctx, "/argcv.app.manul.JobService/GetJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error) {
	out := new(CancelJobResponse)
	err := c.cc.Invoke(ctx, "/argcv.app.manul.JobService/CancelJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobServiceServer is the server API for JobService service.
type JobServiceServer interface {
	// List Jobs
	ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error)
	CreateJob(context.Context, *CreateJobRequest) (*CreateJobResponse, error)
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
	CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error)
}

func RegisterJobServiceServer(s *grpc.Server, srv JobServiceServer) {
	s.RegisterService(&_JobService_serviceDesc, srv)
}

func _JobService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/argcv.app.manul.JobService/ListJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).ListJobs(ctx, req.(*ListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/argcv.app.manul.JobService/CreateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).CreateJob(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/argcv.app.manul.JobService/GetJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/argcv.app.manul.JobService/CancelJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JobService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "argcv.app.manul.JobService",
	HandlerType: (*JobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListJobs",
			Handler:    _JobService_ListJobs_Handler,
		},
		{
			MethodName: "CreateJob",
			Handler:    _JobService_CreateJob_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _JobService_GetJob_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _JobService_CancelJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "argcv/proto/app/manul/job.proto",
}
